stages:
  - lint
  - test

variables:

  npm_config_cache: "$CI_PROJECT_DIR/.npm"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

# ---- LINT ----
lint:
  stage: lint
  image: node:20-alpine
  script:
    - npm ci
    - npx eslint .
  only:
    - merge_requests
    - branches

# ---- TEST ----
test:
  stage: test
  image: node:20-alpine
  services:
    - name: postgres:16-alpine
      alias: db
  variables:
    POSTGRES_HOST: db
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: myapp
  script:
    - npm ci
    - npm run test
  only:
    - merge_requests
    - branches
