
services:
  api:
    build: .
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui:v5.0.0
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi:ro   
    ports:
      - "8080:8080"
    depends_on:
      - api

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

volumes:
  pgdata:
